ifpen/chalk-it

front-end/source/angular/modules/dashboard/_partials/panels/dashboard_aspects.html
front-end/source/angular/modules/dashboard/_partials/panels/dashboard_libraries.controller.js
front-end/source/angular/modules/dashboard/_partials/panels/dashboard_libraries.html
front-end/source/angular/modules/sidebar/sidebar.controller.js
front-end/source/kernel/base/xdash-load.js

- Resolve issue with template routes not rendering correctly
- Correct the loading of pyodide libraries

Fix angular routing & pydodide bugs

---

front-end/source/angular/modules/sidebar/sidebar.controller.js
front-end/source/assets/style/layout/_sidebar.scss

Maintain the original project name format in the list of projects to open

Disable capital-case for project list #12

---

front-end/source/kernel/dashboard/plugins/basic/plugin-flat-ui-complex-widgets.js
front-end/source/kernel/dashboard/plugins/geo-time/plugin-flat-ui-address-completion.js
front-end/source/kernel/dashboard/plugins/widget-base.js

Addition of a new graphical property to the table widget: "backgroundColor" that has two values "primary" and "secondary"

feat: add striped background color to table widget

---

front-end/source/angular/modules/dashboard/_partials/modals/exportDownloadModal.controller.js
front-end/source/angular/modules/dashboard/_partials/modals/exportDownloadPage.html
front-end/source/angular/modules/dashboard/_partials/panels/dashboard_aspects.html
front-end/source/angular/modules/modals/info_project.controller.js
front-end/source/kernel/base/xdash-main.js
front-end/source/kernel/dashboard/plugins/plots/plugin-plotly-widgets.js
front-end/source/kernel/dashboard/scaling/layout-mgr.js
front-end/source/kernel/general/export/runtime-toolbar.js
front-end/source/kernel/general/interfaces/xdash-api.js
front-end/source/kernel/runtime/custom-navigation-runtime.js
front-end/source/kernel/runtime/row-to-page-runtime.js
front-end/source/kernel/runtime/row-to-tab-runtime.js
front-end/source/kernel/runtime/xdash-runtime-main.js

Bug fixes for the following scaling methods:
- projectToTargetWindow
- rowToPage
- rowToTab
- customNavigation

fix scaling methods bug

---

front-end/source/assets/style/_utils.scss
front-end/source/assets/style/layout/_aside.scss

fix blank space #27

---

front-end/source/kernel/datanodes/plugins/plugin-python-script.js

fix: Python datanode regression bug (#53)

---

front-end/gulpFiles/JsFiles.json
front-end/source/kernel/base/xdash-main.js
front-end/source/kernel/datanodes/base/DatanodesListModel.js
front-end/source/kernel/datanodes/execution-engine/DatanodeScheduler.js
front-end/source/kernel/datanodes/plugins/clearobject.mqtt.plugin.js
front-end/source/kernel/datanodes/plugins/plugin-clock.js
front-end/source/kernel/datanodes/plugins/plugin-csv-file.js
front-end/source/kernel/datanodes/plugins/plugin-csv-play.js
front-end/source/kernel/datanodes/plugins/plugin-generic-binary-file.js
front-end/source/kernel/datanodes/plugins/plugin-generic-text-file.js
front-end/source/kernel/datanodes/plugins/plugin-geolocation.datanodes.js
front-end/source/kernel/datanodes/plugins/plugin-json-delay.js
front-end/source/kernel/datanodes/plugins/plugin-json-formula.js
front-end/source/kernel/datanodes/plugins/plugin-json-memory.js
front-end/source/kernel/datanodes/plugins/plugin-json-var.js
front-end/source/kernel/datanodes/plugins/plugin-pyodide.js
front-end/source/kernel/datanodes/plugins/plugin-rest-webservice.js
front-end/source/kernel/datanodes/plugins/plugin-unzip-file.js
front-end/source/kernel/datanodes/plugins/plugin-websocket.receive.datanodes.js
front-end/source/kernel/datanodes/plugins/plugin-websocket.send.datanodes.js

Update AutoStart and ExplicitTrig functionnalies:
- AutoStart  button is set to "YES" by default: If "YES", the dataNode is executed automatically at start (project load, its creation/modification).
- ExplicitTrig button is set to "NO" by default. If "YES", the dataNode is executed only if triggered explicitly (no execution when its predecessors are updated). It is executed automatically once when AutoStart is “YES”.

Triggers upgrade

---

front-end/source/assets/style/widgets/_widgets-buttons.scss
front-end/source/assets/style/widgets/_widgets-forms.scss
front-end/source/kernel/dashboard/connection/widget-datanode-update.js
front-end/source/kernel/dashboard/plugins/basic/plugin-flat-ui-widgets.js
front-end/source/kernel/dashboard/plugins/widget-base.js

fix CSS issues, the loading icon and HTML tags

fix: flatUiButton widget display

---

front-end/source/kernel/dashboard/plugins/basic/plugin-flat-ui-complex-widgets.js
front-end/source/kernel/dashboard/plugins/widget-base.js

New property added:
"selectValueFontSize" reduces the minimum size of combo boxes (selection widgets) to 27px.
"selectValueFontFamily" specifies the font family for the options and selected value.

feat: reduce minimum size for combo box #55

---

front-end/source/kernel/dashboard/connection/widget-datanode-update.js

previous commit was incomplete

fix bug #60

---

front-end/source/assets/style/widgets/_widgets-forms.scss
front-end/source/kernel/dashboard/plugins/basic/plugin-flat-ui-boolean-widgets.js

Added "labelPosition" property to checkbox and switch widgets.

feat: add labelPosition prop to checkbox & switch

---

front-end/source/kernel/dashboard/plugins/geo-time/plugin-calendar-d3-widget.js

fix: calendar widget #88

---

front-end/source/kernel/dashboard/plugins/basic/plugin-flat-ui-complex-widgets.js

fix: multi select widget issue #97

---

front-end/gulpFiles/JsFiles.json
front-end/source/kernel/datanodes/execution-engine/FormulaInterpreter.js
front-end/source/kernel/datanodes/plugins/plugin-json-var.js
front-end/source/kernel/general/interfaces/chalkit-api.js

rename API and impbrove its parsing

New features scheduling

---

front-end/source/kernel/datanodes/execution-engine/FormulaInterpreter.js

fix gotToPage api

---

front-end/source/kernel/general/interfaces/chalkit-api.js
front-end/source/kernel/general/interfaces/xdash-api.js

deep copy for chalkit api

---

documentation/docs/ds/ds-execution-engine.md
documentation/docs/ds/ds-reference.md

update memory and triggers doc

Documentation

---

front-end/source/kernel/dashboard/plugins/basic/plugin-double-slider-widgets.js
front-end/source/kernel/dashboard/plugins/basic/plugin-flat-ui-widgets.js
front-end/source/kernel/dashboard/rendering/preview-widgets.js
front-end/source/kernel/datanodes/base/DatanodeModel.js
front-end/source/kernel/general/interfaces/chalkit-api.js
front-end/source/kernel/general/interfaces/xdash-api.js

remove doubleTrig flag

---

front-end/source/kernel/dashboard/plugins/geo-time/plugin-map-widgets.js

add opacity configuration for imageOverlay via Leaflet Options

add options : image overlay

---

front-end/source/kernel/datanodes/gui/JSEditor.js

add instruction how to use debugger keyword #152

---

back_end/app/server.py

"GetPythonDataList" is a POST endpoint

---

documentation/Templates/Projects/editable-table-2D.xprjson
front-end/source/kernel/dashboard/plugins/annotation-scoring/plugin-markdown-widgets.js
front-end/source/kernel/datanodes/gui/PluginEditor.js
front-end/source/kernel/datanodes/plugins/plugin-csv-play.js
front-end/source/kernel/datanodes/plugins/plugin-json-formula.js

Closes #109
Also fix:
- file import in Generic_file_reader_plugin
- CSV datanodes

109 editable table 2d template regression

---

back_end/taipy/__init__.py
back_end/taipy/chalkit_manager.py
front-end/source/connectors/taipy/taipy-manager.js

Add "chlkt_" at the beginning and "_" at the end of each variable and function name

feat: rename chalk'it manager variables & functions

---

front-end/source/kernel/dashboard/plugins/basic/plugin-flat-ui-widgets.js

updates the push-button widget's actuator type according to whether taipy-link is activated or not.

feat: update actuator type for push-button widget

---

back_end/taipy/chalkit_manager.py
front-end/source/connectors/taipy/taipy-manager.js

- Update taipy notifications
- Added python typing to chalkit_manager code
- Added error exception to file manager code

feat: update taipy notify

---

front-end/source/kernel/general/export/html-export.js

Add munually the taipy resource handler cookie

fix: loading the dashboard at runtime

---

front-end/source/angular/modules/dashboard/_partials/panels/dashboard_aspects.html
front-end/source/assets/style/layout/_aside.scss
front-end/source/kernel/dashboard/scaling/layout-mgr.js

feat: add the “disabled” class to the background color field #279

---

back_end/middleware/pyproject.toml
back_end/middleware/src/chalkit_python_api/public_api.py
back_end/middleware/src/chalkit_python_api/state.py
back_end/middleware/test/capture_test.py
documentation/docs/chalkitapi.md
front-end/.env.dev
front-end/.env.prod
front-end/.env.sample
front-end/chalkit_python_api-0.0.4-py3-none-any.whl
front-end/chalkit_python_api-0.0.5-py3-none-any.whl
front-end/source/kernel/datanodes/plugins/plugin-python-support.js

Split dashboard API into dashboard and scheduler

---

front-end/source/kernel/base/xdash-data-updates.js

fix compatibility with old xprjson (data.dataNodes) #311

---

front-end/source/kernel/dashboard/plugins/geo-time/plugin-timepicker-widgets.js

fix time picker icon missiong #307

---

front-end/index_tmp.html
front-end/source/angular/modules/cards/cards.html
front-end/source/assets/style/layout/_main.scss

add scoll to templates view #319

---

front-end/source/kernel/runtime/xdash-runtime-main.js

fix bug in decoding html entities

---

front-end/source/kernel/dashboard/rendering/preview-widgets.js
front-end/source/kernel/runtime/xdash-runtime-main.js

"AdjustToFullWidth":
"keepOriginalWidth":

feat: improve scaling methods

---

front-end/source/kernel/runtime/custom-navigation-runtime.js

fix: custom navigation runtime bug #334

---

front-end/source/assets/style/widgets/_widgets.scss
front-end/source/kernel/dashboard/plugins/annotation-scoring/plugin-annotation-widgets.js

- led light
- calendar 3D undefined color
- image load

337 fix fonts regressions after dark mode application

---

front-end/source/kernel/dashboard/rendering/preview-widgets.js

fix None widget binding #333

---

front-end/source/kernel/dashboard/plugins/basic/plugin-flat-ui-widgets.js

#341 done 
examples here: [events.json](https://github.com/user-attachments/files/16096101/events.json)

341 numerical input and progress bar real time updates

---

back_end/middleware/src/chalkit_python_api/public_api.py
back_end/middleware/src/chalkit_python_api/state.py
back_end/middleware/test/capture_test.py
front-end/source/kernel/datanodes/execution-engine/FormulaInterpreter.js
front-end/source/kernel/datanodes/plugins/plugin-python-support.js
front-end/source/kernel/general/interfaces/chalkit-api.js

#192 implemented from chalkit side
example for use: [notify.xprjson.json](https://github.com/user-attachments/files/16101076/notify.xprjson.json)

192 implement chalkit notification api

---

front-end/source/kernel/dashboard/plugins/annotation-scoring/plugin-annotation-widgets.js
front-end/source/kernel/dashboard/plugins/annotation-scoring/plugin-generic-html-widgets.js
front-end/source/kernel/dashboard/plugins/annotation-scoring/plugin-markdown-widgets.js
front-end/source/kernel/dashboard/plugins/annotation-scoring/plugin-scoring-widgets.js
front-end/source/kernel/dashboard/plugins/basic/plugin-double-slider-widgets.js
front-end/source/kernel/dashboard/plugins/basic/plugin-flat-ui-boolean-widgets.js
front-end/source/kernel/dashboard/plugins/basic/plugin-flat-ui-complex-widgets.js
front-end/source/kernel/dashboard/plugins/basic/plugin-flat-ui-widgets.js
front-end/source/kernel/dashboard/plugins/basic/plugin-kpi-advanced-widgets.js
front-end/source/kernel/dashboard/plugins/basic/plugin-kpi-widgets.js
front-end/source/kernel/dashboard/plugins/basic/plugin-load-file-widgets.js
front-end/source/kernel/dashboard/plugins/basic/plugin-save-to-file-widgets.js
front-end/source/kernel/dashboard/plugins/basic/plugin-spinner-status-widgets.js
front-end/source/kernel/dashboard/plugins/gauges/plugin-led-light.js
front-end/source/kernel/dashboard/plugins/geo-time/plugin-calendar-d3-widgets.js
front-end/source/kernel/dashboard/plugins/geo-time/plugin-datepicker-widgets.js
front-end/source/kernel/dashboard/plugins/geo-time/plugin-daterangepicker-widgets.js
front-end/source/kernel/dashboard/plugins/geo-time/plugin-flat-ui-address-completion.js
front-end/source/kernel/dashboard/plugins/geo-time/plugin-map-widgets.js
front-end/source/kernel/dashboard/plugins/geo-time/plugin-timepicker-widgets.js
front-end/source/kernel/dashboard/plugins/plots/plugin-echarts-widgets.js
front-end/source/kernel/dashboard/plugins/plots/plugin-plotly-widgets.js
front-end/source/kernel/dashboard/plugins/plots/plugin-python-widgets.js
front-end/source/kernel/dashboard/plugins/plots/plugin-vega-widgets.js
front-end/source/kernel/dashboard/plugins/widget-base.js
front-end/source/kernel/general/interfaces/chalkit-api.js

fix show/hide widget api #351

---

front-end/source/assets/style/layout/_editor-mode.scss

fix drag&drop from image #353

---

front-end/source/angular/modules/dashboard/_partials/editor/editor.html
front-end/source/angular/modules/editor/editor.controller.js

add option in context menu #357

---

front-end/source/kernel/datanodes/base/DatanodesManager.js

regression: add missing codes #355

---

front-end/source/kernel/dashboard/plugins/basic/plugin-flat-ui-complex-widgets.js

- solve table rendering regression in view mode

fix issue #413

---

front-end/source/assets/style/widgets/leaflet/_leaflet.scss

fix issue #412

---

README.md

needed dashboard.xprjson not application.xprjson

Fix Docker file error

---

front-end/source/kernel/dashboard/plugins/basic/plugin-flat-ui-complex-widgets.js

fix: "multi-selection” widget display in view mode #439

---

front-end/source/kernel/dashboard/plugins/basic/plugin-flat-ui-complex-widgets.js

fix: center the content of the "multiselect" widget #439

---

front-end/source/kernel/dashboard/plugins/basic/plugin-flat-ui-complex-widgets.js

fix: rendering of "select" widget at runtime #430

---

front-end/source/angular/modules/dashboard/_partials/panels/dashboard_datanodes.html

style: correction of the search result text in the datanode panel #408

---

front-end/source/kernel/dashboard/edition/edit-widgets.js

Do not touch the selection when loading a dashboard

---

front-end/source/angular/modules/dashboard/_partials/panels/dashboard_aspects.html
front-end/source/angular/modules/editor/editor.controller.js

455 setting a dashboard size with 0 margins does not work

---

front-end/source/angular/modules/dashboard/_partials/panels/dashboard_aspects.html

Default submit fell onto the "Fit width" button.
fixes #456

Define buttons as just buttons.

---

back_end/app/server.py
front-end/source/kernel/runtime/xdash-runtime-main.js

450 run with command chalk it render myxprjson

---

front-end/source/kernel/dashboard/rendering/widget-viewer.js
front-end/source/kernel/datanodes/execution-engine/FormulaInterpreter.js
front-end/source/kernel/general/interfaces/chalkit-api.js

461 showhidedisableenable widget functions do not work

---

front-end/source/angular/modules/editor/editor.actions.js
front-end/source/kernel/dashboard/rendering/widget-editor-viewer.js
front-end/source/kernel/dashboard/rendering/widget-viewer.js

463 multiple z order problems

---

front-end/source/angular/modules/dashboard/_partials/dashboard_contentTop.controller.js

Correct invalid name

---

front-end/source/angular/modules/dashboard/services/edit-play-switch.js
front-end/source/kernel/dashboard/rendering/widget-viewer.js
front-end/source/kernel/runtime/xdash-runtime-main.js

currentPage is needed when creating widgets

---

front-end/source/kernel/base/xdash-main.js
front-end/source/kernel/dashboard/rendering/widget-viewer.js
front-end/source/kernel/datanodes/base/DatanodesListModel.js
front-end/source/kernel/datanodes/base/DatanodesManager.js
front-end/source/kernel/datanodes/export/xdsjson.js
front-end/source/kernel/runtime/xdash-runtime-main.js

Split datanodes creation from the scheduler start

---

front-end/source/kernel/dashboard/rendering/widget-viewer.js

Dashboard's margins do not use HTML padding in view mode

---

front-end/source/angular/modules/dashboard/services/edit-play-switch.js
front-end/source/kernel/base/xdash-main.js
front-end/source/kernel/dashboard/rendering/widget-viewer.js
front-end/source/kernel/runtime/xdash-runtime-main.js

assignValueChangeHandlers needs "constants" datanodes processed

---

front-end/source/kernel/dashboard/rendering/widget-viewer.js

when widget is hidden, it's z-order shall be 0

Fix chalkit.show/hide widget issues with z-order

---

front-end/source/kernel/dashboard/plugins/basic/plugin-flat-ui-complex-widgets.js

fix: multi-select widget value update #493

---

front-end/source/assets/style/layout/_common.scss

solve issue #496

---

front-end/source/kernel/base/xdash-main.js
front-end/source/kernel/runtime/xdash-runtime-main.js

fix: avoid save pop-up window #498

---

front-end/source/angular/modules/editor/editor.actions.js

fix: clear dashboard #505

---

front-end/source/kernel/dashboard/plugins/basic/plugin-flat-ui-complex-widgets.js

- Bug fixes regarding selection/unselection
- More consistent behavior
- Enable unselect if click on already selected item

Enhance list widget
